name: chatfusion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shadcn_flutter:
    git:
      url: "https://github.com/sunarya-thito/shadcn_flutter.git"
  bitsdojo_window: ^0.1.6
  flutter_acrylic: ^1.1.4
  go_router: ^14.8.1
  easy_image_viewer: ^1.5.1
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.6+2
  highlight: ^0.7.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  dart_openai: ^5.1.0
  dart_openai_plus: ^1.0.0
  flutter_svg: ^2.0.17
  easy_localization: ^3.0.7+1
  get: ^4.7.2
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/translations/
    - .env
